### ISSUE TITLE
text should be placed on the image

### ISSUE THREAD

**Issue by dev-lovedeep** [ContriHUB/Meme-Generator#5]
currently, the text is below the image. Make changes such that the text is shown on the image

**Comment by dev-lovedeep** [comment]
depends on issue #4

**Comment by codeboyfriend** [comment]
Change the position of the text to absolute nd apply the left, right, top or bottom value

**Comment by KIRTIKUMARKK21** [comment]
@dev-lovedeep can you please assign me this issue? I have fixed the image-text position (issue #7 and issue#5). User can now drag the text to wherever place.

**Comment by dev-lovedeep** [comment]
> @dev-lovedeep can you please assign me this issue? I have fixed the image-text position (issue #7 and issue#5). User can now drag the text to wherever place.

request issue from contrihub website [https://contri-hub.herokuapp.com/](url) and do not solve an issue until assigned. your hard work may go into vain.
